# Generated by Django 4.1.2 on 2022-11-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='phone',
            field=models.CharField(max_length=128, null=True, verbose_name='Контакты организации'),
        ),
    ]
