# Generated by Django 4.1.2 on 2022-11-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_partners_email_alter_partners_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='urls',
            field=models.CharField(max_length=50, null=True, verbose_name='Ссылка на сайт'),
        ),
    ]
