# Generated by Django 4.1.2 on 2022-11-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_partners_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='volunteers_photo')),
                ('full_name', models.CharField(max_length=20, verbose_name='Имя волонтера')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес проживания')),
                ('phone', models.CharField(max_length=12, verbose_name='Контактный номер')),
                ('email', models.CharField(max_length=50, verbose_name='Электронная почта')),
                ('education', models.TextField(verbose_name='Образование')),
            ],
            options={
                'verbose_name': 'Волонтер',
                'verbose_name_plural': 'Волонтеры',
            },
        ),
        migrations.AlterField(
            model_name='partners',
            name='avatar',
            field=models.ImageField(upload_to='partners_image'),
        ),
    ]
