# Generated by Django 4.1.2 on 2022-11-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=256, null=True, verbose_name='Адрес прожвания'),
        ),
    ]
