# Generated by Django 4.1.2 on 2022-12-03 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionplaces',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_collection_places', verbose_name='Фото точек приема пользователя')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование организации')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес организации')),
                ('phone', models.CharField(max_length=128, null=True, verbose_name='Контакты организации')),
                ('working_from', models.CharField(max_length=10, verbose_name='Время открытия')),
                ('working_to', models.CharField(max_length=10, verbose_name='Время закрытия')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('material_type', models.ManyToManyField(related_name='posts', to='main.materialtype')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
