# Generated by Django 4.1.2 on 2022-12-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_partners_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
