# Generated by Django 4.1.2 on 2023-04-03 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_collectionplaces_material_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование пункта')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес пункта')),
                ('phone', models.CharField(max_length=128, verbose_name='Контактный номер')),
                ('working_hours', models.CharField(max_length=100, null=True, verbose_name='График работы')),
                ('photo', models.ImageField(upload_to='collection_places', verbose_name='Картинка')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='Электронная почта')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
