# Generated by Django 4.1.2 on 2023-05-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_userposts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionplaces',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='collectionplaces',
            name='material_type',
            field=models.ManyToManyField(to='main.materialtype'),
        ),
        migrations.AlterField(
            model_name='collectionplaces',
            name='photo',
            field=models.ImageField(upload_to='media/collection_places/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='collectionplaces',
            name='working_hours',
            field=models.CharField(max_length=100, verbose_name='График работы'),
        ),
    ]
