# Generated by Django 4.1.2 on 2023-05-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_collectionplaces_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionplaces',
            name='photo',
            field=models.ImageField(upload_to='collection_places', verbose_name='Картинка'),
        ),
    ]
